name: emotion_ai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.1
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.2.3
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  flutter_blue: ^0.8.0

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

